@startuml

title __MODEL's Class Diagram__\n

    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.City {
            # ID : int
            # countryCode : String
            # lat : double
            # lon : double
            # name : String
            + City()
            + getCountryCode()
            + getID()
            + getLat()
            + getLon()
            + getName()
            + printCity()
            + setCountryCode()
            + setID()
            + setLat()
            + setLon()
            + setName()
        }
      }
    }


    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.Country {
            ~ cities : ArrayList<City>
            ~ countryCode : String
            + Country()
            + addCity()
            + getCities()
            + getCityIDByName()
            + getCountryCode()
            + printCityList()
        }
      }
    }

  

    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.Places {
            - countryList : ArrayList<Country>
            - inputFileName : String
            + Places()
            + getCountryList()
            + modelInit()
            + printPlaces()
            - addCity()
        }
      }
    }

  

    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.WeatherAPI {
            - APIKey : String
            - APIURL : String
            - jsonResponse : String
            + WeatherAPI()
            + getWeatherInfo()
            - fetchIcon()
            - parseJSON()
            - queryWeatherServer()
        }
      }
    }

  


    namespace o.mta.se.lab {
      namespace model {
        class ro.mta.se.lab.model.WeatherInfo {
            # cityName : String
            # description : String
            # feelsLike : String
            # humidity : String
            # iconCode : String
            # image : Image
            # pressure : String
            # tempMax : String
            # tempMin : String
            # temperature : String
            # windSpeed : String
            + WeatherInfo()
            + getCityName()
            + getDescription()
            + getFeelsLike()
            + getHumidity()
            + getIconCode()
            + getImage()
            + getPressure()
            + getTempMax()
            + getTempMin()
            + getTemperature()
            + getWindSpeed()
        }
      }
    }

  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
